=== lxmx/pekwm-theme-index/theme.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://github.com/pekdon/pekwm-theme-registry/theme.schema.json",
    "title": "pekwm theme",
    "description": "A pekwm theme in the pekwm theme registry",
    "type": "object",
    "properties": {
        "registry-version": {
            "description": "Registry format version",
            "type": "integer",
            "const": 1
        },
        "author": {
            "description": "Theme author",
            "type": "string"
        },
        "original-theme-author": {
            "description": "Author of the original version of the theme, set if it is a theme port",
            "type": "string"
        },
        "original-theme-homepage": {
            "description": "Homepage of the original version of the theme (or of the original theme author), set if it is a theme port",
            "type": "string",
            "format": "uri"
        },
        "original-theme-wm": {
            "description": "Window Manager / OS of the original theme",
            "type": "string",
            "pattern": "^[a-zA-Z0-9][a-zA-Z0-9_-]*$"
        },
        "name": {
            "description": "Theme name",
            "type": "string",
            "pattern": "^[a-zA-Z0-9][a-zA-Z0-9_-]*$"
        },
        "title": {
            "description": "Theme title, used in theme listing",
            "type": "string",
            "maxLength": 79
        },
        "description": {
            "description": "Theme description",
            "type": "string"
        },
        "homepage": {
            "description": "Theme homepage",
            "type": "string",
            "format": "uri"
        },
        "source": {
            "type": "object",
            "properties": {
                "type": {
                    "type": "string",
                    "enum": ["git", "http"]
                },
                "git": {
                    "type": "object",
                    "properties": {
                        "remote": {
                            "type": "string",
                            "format": "uri"
                        },
                        "branch": {
                            "type": "string"
                        }
                    },
                    "required": ["remote", "branch"]
                },
                "http": {
                    "type": "object",
                    "properties": {
                        "url": {
                            "type": "string",
                            "format": "uri"
                        }
                    },
                    "required": ["url"]
                }
            },
            "required": ["type"]
        }
    },
    "required": ["registry-version",
                 "author",
                 "name",
                 "title",
                 "source"]
}

=== lxmx/pekwm-theme-index/themes/detour.json
{
    "registry-version": 1,

    "author": "Oliver Kraitschy",
    "original-theme-author": "Alberto Castro",
    "original-theme-wm": "E17",
    "name": "Detour",
    "title": "Detour theme for pekwm",
    "homepage": "https://github.com/okraits/pekwm-theme-detour",
    "source": {
        "type": "git",
        "git": {
            "remote": "https://github.com/okraits/pekwm-theme-detour.git",
            "branch": "main"
        }
    }
}

=== lxmx/pekwm-theme-index/themes/ion-p.json
{
    "registry-version": 1,

    "author": "Claes Nästén",
    "name": "ion-p",
    "title": "ION styled themes for pekwm",
    "homepage": "https://github.com/pekdon/pekwm-theme-ion-p",
    "source": {
        "type": "git",
        "git": {
            "remote": "https://github.com/pekdon/pekwm-theme-ion-p.git",
            "branch": "main"
        }
    }
}

=== lxmx/pekwm-theme-index/themes/pwm-p.json
{
    "registry-version": 1,

    "author": "Claes Nästén",
    "name": "pwm-p",
    "title": "PWM styled themes for pekwm",
    "homepage": "https://github.com/pekdon/pekwm-theme-pwm-p",
    "source": {
        "type": "git",
        "git": {
            "remote": "https://github.com/pekdon/pekwm-theme-pwm-p.git",
            "branch": "main"
        }
    }
}

=== lxmx/pekwm-theme-index/themes/4dwm_based.json
{
    "registry-version": 1,

    "author": "Paulo Silva",
    "name": "4dwm_based",
    "title": "4dwm_based",
    "description": "This is just a PekWM theme superficially based on SGI Irix 4DWM window manager - the button, decoration bevel and window title text arrangement is different from the original, and the button icons changes on mouse over and pressed behaviours (the original 4DWM ones doesn't do this).",
    "homepage": "https://notabug.org/nitrofurano/pekwmthemes",
    "source": {
        "type": "git",
        "git": {
            "remote": "https://notabug.org/nitrofurano/pekwmthemes.git",
            "branch": "master"
        },
        "base-path": "themes/4dwm_based"
    }
}

=== lxmx/pekwm-theme-index/themes/NeoMotif.json
{
    "registry-version": 1,

    "author": "Paulo Silva",
    "name": "NeoMotif",
    "title": "NeoMotif",
    "description": "An embrionary stage of a Motif-like theme for PekWM",
    "homepage": "https://notabug.org/nitrofurano/pekwmthemes",
    "source": {
        "type": "git",
        "git": {
            "remote": "https://notabug.org/nitrofurano/pekwmthemes.git",
            "branch": "master"
        },
        "base-path": "themes/NeoMotif"
    }
}

=== lxmx/pekwm-theme-index/themes/minimal4dwm.json
{
    "registry-version": 1,

    "author": "Paulo Silva",
    "name": "minimal4dwm",
    "title": "minimal4dwm",
    "description": "",
    "homepage": "https://notabug.org/nitrofurano/pekwmthemes",
    "source": {
        "type": "git",
        "git": {
            "remote": "https://notabug.org/nitrofurano/pekwmthemes.git",
            "branch": "master"
        },
        "base-path": "themes/minimal4dwm"
    }
}
