=== lxmx/pekwm-theme-index/theme.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://github.com/pekdon/pekwm-theme-registry/theme.schema.json",
    "title": "pekwm theme",
    "description": "A pekwm theme in the pekwm theme registry",
    "type": "object",
    "properties": {
        "registry-version": {
            "description": "Registry format version",
            "type": "integer",
            "const": 1
        },
        "author": {
            "description": "Theme author",
            "type": "string"
        },
        "original-theme-author": {
            "description": "Author of the original version of the theme, set if it is a theme port",
            "type": "string"
        },
        "original-theme-homepage": {
            "description": "Homepage of the original version of the theme (or of the original theme author), set if it is a theme port",
            "type": "string",
            "format": "uri"
        },
        "original-theme-wm": {
            "description": "Window Manager / OS of the original theme",
            "type": "string",
            "pattern": "^[a-zA-Z0-9][a-zA-Z0-9_-]*$"
        },
        "name": {
            "description": "Theme name",
            "type": "string",
            "pattern": "^[a-zA-Z0-9][a-zA-Z0-9_-]*$"
        },
        "title": {
            "description": "Theme title, used in theme listing",
            "type": "string",
            "maxLength": 79
        },
        "description": {
            "description": "Theme description",
            "type": "string"
        },
        "homepage": {
            "description": "Theme homepage",
            "type": "string",
            "format": "uri"
        },
        "source": {
            "type": "object",
            "properties": {
                "type": {
                    "type": "string",
                    "enum": ["git", "http"]
                },
                "git": {
                    "type": "object",
                    "properties": {
                        "remote": {
                            "type": "string",
                            "format": "uri"
                        },
                        "branch": {
                            "type": "string"
                        }
                    },
                    "required": ["remote", "branch"]
                },
                "http": {
                    "type": "object",
                    "properties": {
                        "url": {
                            "type": "string",
                            "format": "uri"
                        }
                    },
                    "required": ["url"]
                }
            },
            "required": ["type"]
        }
    },
    "required": ["registry-version",
                 "author",
                 "name",
                 "title",
                 "source"]
}

=== lxmx/pekwm-theme-index/themes/default.json
{
    "registry-version": 1,

    "author": "adriano.src",
    "name": "default",
    "title": "pekwm default theme by adriano.src",
    "source": {
        "type": "git",
        "git": {
            "remote": "https://github.com/pekdon/pekwm.git",
            "branch": "master"
        },
        "base-path": "data/themes/default"
    }
}

=== lxmx/pekwm-theme-index/themes/windowmakerbased_4lba.json
{
    "registry-version": 1,

    "author": "Paulo Silva",
    "name": "windowmakerbased_4lba",
    "title": "WindowMaker-based",
    "description": "This one was a bit based on WindowMaker window decoration - the buttons are a bit different, all arranged in the left side, and they all have hover and press behaviours.",
    "homepage": "https://notabug.org/nitrofurano/pekwmthemes",
    "source": {
        "type": "git",
        "git": {
            "remote": "https://notabug.org/nitrofurano/pekwmthemes.git",
            "branch": "master"
        },
        "base-path": "themes/windowmakerbased_4lba"
    }
}

=== lxmx/pekwm-theme-index/themes/mikachuflat.json
{
    "registry-version": 1,

    "author": "Paulo Silva",
    "name": "mikachuflat",
    "title": "mikachuflat",
    "description": "",
    "homepage": "https://notabug.org/nitrofurano/pekwmthemes",
    "source": {
        "type": "git",
        "git": {
            "remote": "https://notabug.org/nitrofurano/pekwmthemes.git",
            "branch": "master"
        },
        "base-path": "themes/mikachuflat"
    }
}

=== lxmx/pekwm-theme-index/themes/default-plain.json
{
    "registry-version": 1,

    "author": "Claes Nästén",
    "name": "default-plain",
    "title": "pekwm default plain theme (no images)",
    "source": {
        "type": "git",
        "git": {
            "remote": "https://github.com/pekdon/pekwm.git",
            "branch": "master"
        },
        "base-path": "data/themes/default-plain"
    }
}

=== lxmx/pekwm-theme-index/themes/lila.json
{
    "registry-version": 1,

    "author": "Claes Nästén",
    "name": "lila",
    "title": "Original theme, previously named purple-p",
    "description": "Original theme from the early days of pekwm, created on Solaris",
    "homepage": "https://github.com/pekdon/pekwm-theme-lila",
    "source": {
        "type": "git",
        "git": {
            "remote": "https://github.com/pekdon/pekwm-theme-lila.git",
            "branch": "main"
        }
    }
}

=== lxmx/pekwm-theme-index/themes/winter.json
{
    "registry-version": 1,

    "author": "Claes Nästén",
    "name": "winter",
    "title": "pekwm 0.3.0 default theme",
    "source": {
        "type": "git",
        "git": {
            "remote": "https://github.com/pekwm/pekwm.git",
            "branch": "master"
        },
        "base-path": "data/themes/winter"
    }
}

=== lxmx/pekwm-theme-index/themes/semitif.json
{
    "registry-version": 1,

    "author": "Paulo Silva",
    "name": "semitif",
    "title": "Semitif",
    "description": "A request of Claes Nästén (PekWM author), which theme i were also very curious to know how fine it would look on PekWM - mostly because it's a bit hard to find Motif-like themes available, which brings so nostalgic memories from all long-time Unix users.",
    "homepage": "https://notabug.org/nitrofurano/pekwmthemes",
    "source": {
        "type": "git",
        "git": {
            "remote": "https://notabug.org/nitrofurano/pekwmthemes.git",
            "branch": "master"
        },
        "base-path": "themes/semitif"
    }
}

=== lxmx/pekwm-theme-index/themes/benu.json
{
    "registry-version": 1,

    "author": "Victor Geraldsson",
    "name": "benu",
    "title": "BeOS style theme for pekwm",
    "homepage": "https://github.com/vicgeralds/benu",
    "source": {
        "type": "git",
        "git": {
            "remote": "https://github.com/vicgeralds/benu.git",
            "branch": "master"
        }
    }
}
